#!/usr/bin/env bash
# Script that installs Nginx server
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw --force enable
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
