#!/usr/bin/env bash
# configures a brand new Ubuntu machine

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo sed -i -e "s+location / {+location / {\n\t\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx restart
