#!/usr/bin/env bash
# Script that configures HAproxy in a load balancer

sudo apt-get -y update
sudo apt-get -y install haproxy
sudo echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 1586-web-01 35.227.37.173:80 check\n\tserver 1586-web-02 18.207.135.118:80 check" >> sudo /etc/haproxy/haproxy.cfg
sudo service haproxy restart
