#!/usr/bin/env bash
# a script that displays "Best School" 9 times and "Hi" one times using while loop and a IF statement
i=1
while [ $i -le 10 ]
do
  echo "Best School"
  if [[ $i -eq 9 ]]
  then
    echo "Hi"
  fi
  ((i++))
done
