#!/usr/bin/env bash
# a script that displays "Best School" 9 times and "good luck" and "bad luck" one times using while loop and a elif if statement
i=1
while [ $i -le 10 ]
do
  if [[ $i -eq 4 ]]
  then
    echo "bad luck"
  elif [[ $i -eq 8 ]]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  ((i++))
done
