#!/usr/bin/env bash
# nginx must be running as nginx user
# nginx must be listening on all active IPs on port 8080
# You cannot use apt-get remove
# a Bash script that configures the container to fit the above requirements

sudo chmod 777 /etc/nginx/nginx.conf
sudo sed -i "s/90/8080/g" /etc/nginx/sites-available/default
sudo sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sudo pkill -9 apache
sudo nginx -c "service nginx restart"
